### ISSUE TITLE
Raising events while creating entity

### ISSUE THREAD

**Issue by iTKerry** [vkhorikov/DddAndEFCore#4]
# Problem
I'm trying to understand of how to raise event while creating entity.
For example, you have next line:
```RaiseDomainEvent(new StudentEmailChangedEvent(Id, email));```
This will raise domain event for existing entity with it unique identifier. 

Is it possible to do the same, but for entities that wasn't stored to DB? Lets say, I want to know when entity was created and for some reason I need his identifier. Probably attach ID at overload of SaveChanges method, or something like that. Which way is correct from DDD perspective for that simple task?

Thanks!

**Comment by vkhorikov** [comment]
Good question, and I should've mentioned this in the course. The more appropriate way to raise events would be by passing them a student instance, not the student id. In fact, the passing of the Id contradicts the guideline I mentioned in the course: that you shouldn't use Ids in the domain layer (which domain events are part of).

So:
- Pass the student instance when instantiating an event
- EF Core will assign the id after saving changes
- Even dispatcher will automatically have the student id to work with

**Comment by iTKerry** [comment]
Thanks for your answer. I just tried and it works like a charm!
