### ISSUE TITLE
Module 5 : Shortcomings of Mapping to Backing Fields (2:23)

### ISSUE THREAD

**Issue by Brimce** [vkhorikov/DddAndEFCore#9]
Maybe you could use [.HasConversion()](https://docs.microsoft.com/fr-fr/ef/core/modeling/value-conversions?tabs=data-annotations) to solve mapping of student property `Maybe<Course> FavoriteCourse `

In any case, thank you for this valuable course !

**Comment by Brimce** [comment]
Module 6 gives the answer: that does not solve the issue

**Comment by vkhorikov** [comment]
Right. It doesn't work with entities as far as I remember.
